# Extracting and sampling

# Setter Default and ignored boolean / statement
null = None
false = False
true = True

# Base Array
datanyah = {
  'base': [
    {"created_at":"Tue Nov 07 07:00:01 +0000 2017","id":9.27792741819601e+017,"id_str":"927792741819600897","text":"Semua orang bisa membuat video yang berkualitas lho, yuk pelajari tips merekam video secara profesional menggunakan smartphone! #TelkomEdu","truncated":false,"entities":{"hashtags":[{"text":"TelkomEdu","indices":[128,138]}],"symbols":[],"user_mentions":[],"urls":[]},"source":"<a href=\"http://sproutsocial.com\" rel=\"nofollow\">Sprout Social<\/a>","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":80204488,"id_str":"80204488"},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":2,"favorite_count":0,"favorited":false,"retweeted":false,"lang":"in"},
    {"created_at":"Tue Nov 07 06:00:11 +0000 2017","id":9.27777684238815e+017,"id_str":"927777684238815232","text":"Petualangan seorang bocah laki-laki bernama Wally Trollman dan naga kesayangan, Norville. Wallykazam 15.05 WIB Nick… https://t.co/xI79lkpTux","truncated":true,"entities":{"hashtags":[],"symbols":[],"user_mentions":[],"urls":[{"url":"https://t.co/xI79lkpTux","expanded_url":"https://twitter.com/i/web/status/927777684238815232","display_url":"twitter.com/i/web/status/9…","indices":[117,140]}]},"source":"<a href=\"http://www.hootsuite.com\" rel=\"nofollow\">Hootsuite<\/a>","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":528328843,"id_str":"528328843"},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":0,"favorite_count":0,"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"in"},
    {"created_at":"Tue Nov 07 04:00:10 +0000 2017","id":9.27747477796741e+017,"id_str":"927747477796741120","text":"Aktifkan HOOQ dari UseeStore &amp; dapatkan bonus TVOD film &amp; serial TV Hollywood setiap bulannya di @HOOQ_ID!… https://t.co/yQMjHMGAka","truncated":true,"entities":{"hashtags":[],"symbols":[],"user_mentions":[{"screen_name":"HOOQ_ID","name":"HOOQ Indonesia","id":3322010498,"id_str":"3322010498","indices":[105,113]}],"urls":[{"url":"https://t.co/yQMjHMGAka","expanded_url":"https://twitter.com/i/web/status/927747477796741120","display_url":"twitter.com/i/web/status/9…","indices":[116,139]}]},"source":"<a href=\"http://www.hootsuite.com\" rel=\"nofollow\">Hootsuite<\/a>","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":528328843,"id_str":"528328843"},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":0,"favorite_count":0,"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"in"},
    {"created_at":"Mon Nov 06 12:00:24 +0000 2017","id":9.27505947039338e+017,"id_str":"927505947039338497","text":"Saksikan rangkaian pertandingan Golf terkini secara gratis hingga 15 Nov 2017 di Golf Channel &amp; Golf+ Subscribe now… https://t.co/1LkYAhQDT8","truncated":true,"entities":{"hashtags":[],"symbols":[],"user_mentions":[],"urls":[{"url":"https://t.co/1LkYAhQDT8","expanded_url":"https://twitter.com/i/web/status/927505947039338497","display_url":"twitter.com/i/web/status/9…","indices":[121,144]}]},"source":"<a href=\"http://www.hootsuite.com\" rel=\"nofollow\">Hootsuite<\/a>","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":528328843,"id_str":"528328843"},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":0,"favorite_count":0,"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"in"},
    {"created_at":"Mon Nov 06 08:00:16 +0000 2017","id":9.27445515125645e+017,"id_str":"927445515125645312","text":"Yuk ikutan kuis #HOOQOriginals Premier Film Marlina Si Pembunuh dlm Empat Babak! Jwb pertanyaannya di… https://t.co/1Fo1P06HUA","truncated":true,"entities":{"hashtags":[{"text":"HOOQOriginals","indices":[16,30]}],"symbols":[],"user_mentions":[],"urls":[{"url":"https://t.co/1Fo1P06HUA","expanded_url":"https://twitter.com/i/web/status/927445515125645312","display_url":"twitter.com/i/web/status/9…","indices":[103,126]}]},"source":"<a href=\"http://www.hootsuite.com\" rel=\"nofollow\">Hootsuite<\/a>","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":528328843,"id_str":"528328843"},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":0,"favorite_count":0,"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"in"},
    {"created_at":"Mon Nov 06 04:29:49 +0000 2017","id":9.27392553103708e+017,"id_str":"927392553103708160","text":"Dont Breathe - Suspense Thriller - HBO: https://t.co/tOyOdcJ27Y via @YouTube","truncated":false,"entities":{"hashtags":[],"symbols":[],"user_mentions":[{"screen_name":"YouTube","name":"YouTube","id":10228272,"id_str":"10228272","indices":[68,76]}],"urls":[{"url":"https://t.co/tOyOdcJ27Y","expanded_url":"http://youtu.be/bHUnHmFVXMs?a","display_url":"youtu.be/bHUnHmFVXMs?a","indices":[40,63]}]},"source":"<a href=\"http://www.google.com/\" rel=\"nofollow\">Google<\/a>","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":528328843,"id_str":"528328843"},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":1,"favorite_count":1,"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"en"},
    {"created_at":"Mon Nov 06 04:00:10 +0000 2017","id":9.27385091889861e+017,"id_str":"927385091889860609","text":"Mau kado natal dari IndiHome? Ikuti promo undian IndiHome Paket Natal &amp; Tahun Baru! Banyak hadiahnya lho!… https://t.co/wo36HBVFi8","truncated":true,"entities":{"hashtags":[],"symbols":[],"user_mentions":[],"urls":[{"url":"https://t.co/wo36HBVFi8","expanded_url":"https://twitter.com/i/web/status/927385091889860609","display_url":"twitter.com/i/web/status/9…","indices":[111,134]}]},"source":"<a href=\"http://www.hootsuite.com\" rel=\"nofollow\">Hootsuite<\/a>","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":528328843,"id_str":"528328843"},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":1,"favorite_count":2,"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"in"},
    {"created_at":"Mon Nov 06 03:21:32 +0000 2017","id":9.2737536854093e+017,"id_str":"927375368540930050","text":"Saksikan pertandingannya mulai Desember 2017 di channel UseePrime no 88 #myIndiHomeIBL #RaiseUP #IBL https://t.co/sjqeMdTSCK","truncated":false,"entities":{"hashtags":[{"text":"myIndiHomeIBL","indices":[72,86]},{"text":"RaiseUP","indices":[87,95]},{"text":"IBL","indices":[96,100]}],"symbols":[],"user_mentions":[],"urls":[{"url":"https://t.co/sjqeMdTSCK","expanded_url":"https://twitter.com/TelkomIndonesia/status/927370883492077568","display_url":"twitter.com/TelkomIndonesi…","indices":[101,124]}]},"source":"<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client<\/a>","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":528328843,"id_str":"528328843"},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":true,"quoted_status_id":9.27370883492078e+017,"quoted_status_id_str":"927370883492077568","quoted_status":{"created_at":"Mon Nov 06 03:03:42 +0000 2017","id":9.27370883492078e+017,"id_str":"927370883492077568","text":"Telkom Indonesia menjadi sponsor pd kompetisi basket terbesar di Indonesia. Selengkapnya cek di… https://t.co/A6mlrLdmmk","truncated":true,"entities":{"hashtags":[],"symbols":[],"user_mentions":[],"urls":[{"url":"https://t.co/A6mlrLdmmk","expanded_url":"https://twitter.com/i/web/status/927370883492077568","display_url":"twitter.com/i/web/status/9…","indices":[97,120]}]},"source":"<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client<\/a>","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":80204488,"id_str":"80204488"},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":7,"favorite_count":12,"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"in"},"retweet_count":1,"favorite_count":1,"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"in"},
    {"created_at":"Mon Nov 06 02:33:30 +0000 2017","id":9.27363280749949e+017,"id_str":"927363280749948928","text":"Aplikasi myIndiHome banyak benefitnya lho! Mau tau apa saja? Download skarang di Google Play&amp;App Store!… https://t.co/59RrG4SxrD","truncated":true,"entities":{"hashtags":[],"symbols":[],"user_mentions":[],"urls":[{"url":"https://t.co/59RrG4SxrD","expanded_url":"https://twitter.com/i/web/status/927363280749948928","display_url":"twitter.com/i/web/status/9…","indices":[109,132]}]},"source":"<a href=\"http://www.hootsuite.com\" rel=\"nofollow\">Hootsuite<\/a>","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":528328843,"id_str":"528328843"},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":1,"favorite_count":2,"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"in"},
    {"created_at":"Sun Nov 05 12:00:32 +0000 2017","id":9.2714359239261e+017,"id_str":"927143592392609792","text":"Ragam acara Korea dan Jepang kini semakin seru dengan hadirnya channel S One dan S Gem di UseeTV! Yuk saksikan dram… https://t.co/DVhu0igSxW","truncated":true,"entities":{"hashtags":[],"symbols":[],"user_mentions":[],"urls":[{"url":"https://t.co/DVhu0igSxW","expanded_url":"https://twitter.com/i/web/status/927143592392609792","display_url":"twitter.com/i/web/status/9…","indices":[117,140]}]},"source":"<a href=\"http://www.hootsuite.com\" rel=\"nofollow\">Hootsuite<\/a>","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":528328843,"id_str":"528328843"},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":3,"favorite_count":1,"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"in"}
  ],
}

bungkus_bracket = []
for element_yeuh in datanyah['base']:
    # if element_yeuh['serial'] == '00000000762c1d3c':
    # print 'there'
    # print  element_yeuh['text']
    bungkus_bracket = element_yeuh['text']
    
    # print bungkus_bracket
    text = [element_yeuh['text']]
    
kamu_d = {}
for words_ajah in datanyah['base']:
    if words_ajah:
        if words_ajah['text'][0] in kamu_d: # Cek Apa ada karakter pertama di kamus yang cacahin
            kamu_d[words_ajah['text'][0]] = kamu_d[words_ajah['text'][0]] + 1 # gunakan karakter pertama sebagai kunci ke kamus
        else: # jika engga ada mari menghihtung
            kamu_d[words_ajah['text'][0]] = 1 # gunakan karakter pertama sebagai kunci ke kamus
    
word_counter_eh = {}
for word_ea in datanyah['base']:
    if word_ea['text'][0] in word_counter_eh:
       word_counter_eh[word_ea['text'][0]] += 1
    else:
         word_counter_eh[word_ea['text'][0]] = 1

words_terkenal = sorted(word_counter_eh, key = word_counter_eh.get, reverse = True)

top_3_terkenal = words_terkenal[:3]

# baru sampe sini
print ("Top 3 Words: ", (top_3_terkenal))
print ("Word_count: ", (kamu_d))

# next -> hashtag_count
# next -> mention_count
# next -> top3_hastagh
# next -> top3_mention